[package]
name = "ziyrak_lib"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html



[dependencies]
ai = { path = "ai" }
model = { path = "model" }
api = { path = "api" }
data_source = { path = "data_source" }